[package]
name = "opsm-shell"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = "1"

[dependencies]
tauri = { version = "1", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
which = "6"

[features]
custom-protocol = ["tauri/custom-protocol"]
